# Ansible Inventory for Kubernetes Cluster
# Auto-generated by Terraform

[masters]
%{ for idx, master in masters ~}
${master.name} ansible_host=${master.network_adapter[0].ipv4_address} ansible_user=vagrant ansible_ssh_private_key_file=~/.ssh/id_rsa
%{ endfor ~}

[workers]
%{ for idx, worker in workers ~}
${worker.name} ansible_host=${worker.network_adapter[0].ipv4_address} ansible_user=vagrant ansible_ssh_private_key_file=~/.ssh/id_rsa
%{ endfor ~}

[k8s_cluster:children]
masters
workers

[k8s_cluster:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
