# SSH Config for Kubernetes Cluster
# Auto-generated by Terraform

%{ for idx, master in masters ~}
Host ${master.name}
    HostName ${master.network_adapter[0].ipv4_address}
    User vagrant
    IdentityFile ~/.ssh/id_rsa
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null

%{ endfor ~}
%{ for idx, worker in workers ~}
Host ${worker.name}
    HostName ${worker.network_adapter[0].ipv4_address}
    User vagrant
    IdentityFile ~/.ssh/id_rsa
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null

%{ endfor ~}
